### ISSUE TITLE
Extract methods from VersionParser.php into it's own package

### ISSUE THREAD

**Issue by nickvergessen** [composer/composer#3545]
[Composer\Package\Version\VersionParser](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php) has some good methods dealing with versions which would be nice to have in a seperate project, so they can be reused instead of either copy pasting them or relying on the whole composer package.

This especially applies to the following methods:
* [parseStability()](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L37)
* [normalizeStability()](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L65)
* [normalize()](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L86)
* [normalizeBranch()](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L86)
* [manipulateVersionString()](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L445)
* [expandStability()](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L479)
* [parseNameVersionPairs()](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L498)

**Comment by legoktm** [comment]
+1

I'm specifically interested in doing this for MediaWiki, where we would like to re-use composer's version parsing code instead of writing our own. I think we would want to include `VersionParser` and all the classes implementing `LinkConstraintInterface`.

VersionParser currently depends on other parts of composer outside of LinkConstraintInterface in:
* parseConstraints - BasePackage::$stabilities
* parseConstraint - BasePackage::$stabilities
* parseLinks - returns Link's
* formatVersion - uses PackageInterface

I don't think it would be too difficult to move those methods somewhere else, and I would be willing to work on a patch that did that.

**Comment by legoktm** [comment]
- [ ] parseConstraints - BasePackage::$stabilities - #4213 
- [ ] parseConstraint - BasePackage::$stabilities - #4213 
- [ ] parseLinks - returns Link's - #4214 
- [x] formatVersion - uses PackageInterface #4086

**Comment by legoktm** [comment]
I think we can close this now that https://github.com/composer/semver exists :)

**Comment by Seldaek** [comment]
https://github.com/composer/semver
