### ISSUE TITLE
Composer v2: Pool/Solver/Repo/Installer Tasks

### ISSUE THREAD

**Issue by naderman** [composer/composer#7630]
- [x] Separate RepositorySet from Pool to allow for clear separation of package loading from dep resolution https://github.com/composer/composer/pull/7625 https://github.com/composer/composer/pull/7629
  - [x] Do not modify package pool during dep resolution
- Pool Builder
  - [x] use version ranges as part of loading mechanism, to potentially allow on-the-fly discarding of JSON data if we add a streaming parser https://github.com/composer/composer/pull/7631
    - [X] For nested dependencies, attempt to determine a union constraint which loads all potential required versions, but not all versions of packages which are deps of deps of the root package or deeper, needs some mechanism to notice that the constraint is getting too complex and it's not worth it, but could be helpful if at least there are simple ranges to be combined https://github.com/composer/composer/pull/7644
    - [ ] improve estimated constraints to replicate performance of dropped old versions in flex
  - [x] don't load package data and generate rules multiple times for identical packages https://github.com/composer/composer/pull/7830
  - [x] fully remove information on installed packages
  - [x] Tests for Pool Builder mechanism https://github.com/composer/composer/commit/921a97457dffbb2e969b54abb13deaa64238c95b
  - [x] do not load unnecessary package data for fixed packages (e.g. partial updates) - see issue https://github.com/composer/composer/issues/3672 - fixed by https://github.com/composer/composer/pull/8531 and https://github.com/composer/composer/pull/8535
- Solver
  - [x] do not involve installed packages, removal operations for all installed packages which are not in the new lock file should be automatic
  - ~~create clear interface that allows replacement (e.g. by sat solver utility on system) related to #6685~~
  - [x] reduce conflict rules - see issue https://github.com/composer/composer/issues/7452
- Error reporting
  - [x] https://github.com/composer/composer/issues/7779
- Installer
  - [x] clean up messy update whitelisting mechanism related https://github.com/composer/composer/issues/8355 and https://github.com/composer/composer/issues/5438 - PR https://github.com/composer/composer/pull/8717
  - [x] update Request class to represent a root composer.json + instructions more directly
- Composer Repository
  - [x] Load named packages directly instead of provider files
  - [x] Load metadata for multiple packages in parallel
  - ~Fully parallelize metadata downloads across multiple repositories~ (cancelled until at least 2.1)

### Memory Reduction
- [x] Combine similar versions in JSON structure on packagist.org (not sure if this is useful considering gzip compression) https://github.com/composer/composer/pull/7904
- ~~Use PackageSet objects which store all packages with the same name and shared metadata - may not be necessary, if we can reduce most strings to a single copy in the original JSON structure as copying them into multiple objects on PHP7 won't use much memory then since the text won't be copied.~~ (should be fixed with new mechanism to load package json data)

**Comment by stof** [comment]
@naderman I think https://github.com/composer/composer/issues/3672 also fits the RepositorySet refactoring (any locked non-whitelisted package should include only the locked package in the RepositorySet, not any coming from remote repositories)

**Comment by naderman** [comment]
@stof yup definitely. I already had "clean up messy update whitelisting mechanism" under Installer, but adding that more explicitly.

**Comment by stof** [comment]
but that's not an installer feature. It is a pool feature (as it is about restricting what the solver can select)

**Comment by naderman** [comment]
@stof the whitelisting is currently in the installer, it's going to be part of the PoolBuilder after we move it there :-)

**Comment by stof** [comment]
@naderman ah, you are talking about the `Composer\Installer` class, which is the code shared between the different commands. I was understanding it as the `Composer\Installer\InstallerInterface` interface and related classes in the `Composer\Installer` namespace, which is a different layer.

**Comment by stof** [comment]
Well, what they do is that they replace the Node resolver behind `require()`, making it transparent to any project which does not inspect the filesystem on its own. That's specific to Node.

For PHP,  most code cares about having autoloadable classes. So this looks like it might be even easier. But the first drawback appears when looking at code needing to require the project autoloader to initialize thing. And while your project can be fine (if we keep it in the same place than today), it would likely cause issues for bin scripts provided by packages (as these ones are entrypoints.

**Comment by Seldaek** [comment]
bin scripts is one issue but it would also break any package writing to the filesystem, or if not break directly then at least add the possibility for super weird behavior. I don't think it's really worth the risk as composer doesn't typically install millions of files like npm tends to do.

**Comment by fabiang** [comment]
> Combine similar versions in JSON structure on packagist.org (not sure if this is useful considering gzip compression)

Maybe for the future, Packagist and Composer could share an compression dictionary for JSON. But unfortunately only ZStandard and LZMA supports passing an predefined compression dictionary via command line (both with the `-d` flag).

There are also PHP extensions for both compression algorithms:
* https://github.com/kjdev/php-ext-zstd
* https://github.com/payden/php-xz

Only the zstd extension supports (de)compression with an dictionary and both extension should only be used rarely on most systems, while `lz4` should be installed on most Linux systems and `zstd` is very uncommon yet.

**Comment by fabiang** [comment]
Sharing a zstd dictionary through HTTP could be done like this: facebook/zstd#315

**Comment by naderman** [comment]
Is this a joke of some sort? You want people to install some obscure PHP extension to be able to use Composer? A working version of reducing JSON has already been implemented in https://github.com/composer/composer/pull/7906 and I don't think this should be discussed in this issue any further.

**Comment by joeyhub** [comment]
> Is this a joke of some sort? You want people to install some obscure PHP extension to be able to use Composer?

The performance of composer is a joke, people are going to be upset and will also start to reach out for any possible solution.

If compression is being proposed for just speeding up downloading of package lists, then make that capabilities based and negotiate, though I pity the fool that only has the xml extension loaded.

If you've got a CDN or proxy layer or something then that can store those, you have control over that so you can make sure it has a good range of serializers and compression.

Composer could check for available serializers and compression routines then select the best. Use accept and accept encoding and just let the HTTP server choose for you.

**Comment by asd-collab** [comment]
> You want people to install some obscure PHP extension to be able to use Composer?

can it be made optional as that would be more desirable, than making it must-have. if the extension is not a mess of code and other requirements being fulfilled.
---

asd-collab

**Comment by joeyhub** [comment]
The thing is I don't see how those extensions would perform miracles. It's compression. LZMA can be impressive for example compared to gzip for compression ratios but we're not looking at 10X. Even using those things should be on an if available basis, IE, negotiate or feature detection. This is coming from having done extensive work with compression benchmarks and having made an LZMA extension for PHP as well as implementing support for zlib streaming in PHP years before it was available natively. My feeling is the bottleneck isn't there or wont be solved with that so easily.

I find it very hard to believe that's the real bottleneck.

Someone should run xdebug profile on it and strace with timestamps and see where the RAM/CPU/IO is all going.

**Comment by joeyhub** [comment]
> just a side-note: the yarn project just published a paper in which they describe, how they wanne completly kill the node_modules/ (aka. vendor/) directory.
> 
> [yarnpkg/rfcs#101](https://github.com/yarnpkg/rfcs/pull/101)
> https://github.com/yarnpkg/rfcs/files/2378943/Plugnplay.pdf
> 
> maybe there is something inside it which can be re-used in composer.

Using a central storage mechanism is a fairly basic 101, although the article talks about it like it's a new revolutionary approach it's actually well known and it's not going to solve the worst problems with composer performance for a lot of people though there is a question of just how good the composer caching really is because for all we know it might not even do that fully effectively. Facebook may have been using that if IE you have a build server making ten, twenty, a hundred things, etc.

Both npm and composer have some annoyances with centralised given they leave out the version. I'm not sure anyone bothered to specify an autoloader in PHP or request something for that (I'm not sure if the auto loader makes it easy to work out where the include is from or not especially with possible load only if the class is missing).

That approach has some drawbacks. A vendor folder will deploy with less hassle otherwise half your application is here and the other half, the dependencies, are over there. You can do interesting things carving out real dependencies except you can't rule out dynamic dependency loading and most people don't have the billions of dollars of extra budget facebook has to have 100% run time coverage in testing to pull out all the runtime dependencies.

**Comment by naderman** [comment]
The only item left here is to now try and build further optimizations into the pool builder, which is tracked in separate issues and can also continue to be improved upon in future 2.x releases without breaking BC or changing any interfaces. Ticket e.g. https://github.com/composer/composer/pull/8295
