### ISSUE TITLE
Solver Issues Summary

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#9294]
There are a number of open issues with tons of repro cases in each which is getting very messy, here is a summary of known test cases which still fail with RC2.

These seem to work in v1 so look more like regressions / higher prio

- [x] https://gist.github.com/Seldaek/cb330c80c333ea191fd5f256447ffb82 minified test case from #9290 which actually triggers a SolverBugException while v1 resolves to an install, looks like a legit regression
- [x] https://gist.github.com/Seldaek/f69ce1b1628c049a5e4903c1feab41a4 minified test case from #9067 which actually triggers a SolverBugException while v1 resolved to a problem exception, looks like a legit regression
- [x] https://gist.github.com/Seldaek/951e27a30398de2db0cacb85c76aa917 minified test cases extracted from OP in #8903, one case resolves quickly and outputs **lots** of problems, the other gets stuck quickly

----

These I think already failed in v1.. they should still be fixed tho for sure if possible.

- [x] https://gist.github.com/naderman/1399cdee05d6d0027890bd0b3e3c0e7f minified case from https://github.com/composer/composer/issues/7665#issuecomment-483069643, never resolves (pass `#1687` and then frozen for hours) - already has a PR open without fix tho in https://github.com/composer/composer/pull/8733
- ~~https://gist.github.com/Seldaek/81ee6492e1e6f8b07d4f4268ccb8d0a2 minified test case from OP in https://github.com/composer/composer/issues/9067 - it resolves and outputs lots of problems, might have been minified too much, not sure~~
- [x] https://gist.github.com/Seldaek/4e2dbc2cea4b4fd7a8207bb310ec8e34 minified test case from OP in #9012 - it gets stuck quickly unless some versions get deleted then it resolves and outputs lots of problems

**Comment by stof** [comment]
@naderman @Seldaek is this expected to be solved before releasing 2.0 as stable in a few days ?

**Comment by naderman** [comment]
@stof Definitely going to try to at least figure out the regression cases, but not entirely decided yet, really depends on the complexity/time required to work this out.

**Comment by Seldaek** [comment]
Closing this as all related issues are closed 🥳
